### PR TITLE
Test User Auth

### PR DESCRIPTION
**Pull request by MarlinTheWiz**
Test if User can be created and saved in Database.
Test if Duplicated Users can be made

Issue #72

### CODE REVIEW

**Comment by PaulL48** [comment]
OK, so now we need to get this pull request ahead of the travis DB setup pull request #85  so that we can see if it passes before merging...
I'm going to look into this now (I think it has something to do with the rebase command)

**Comment by PaulL48** [comment]
Just as an aside though, that is a damn good looking test Marlin

**Comment by PaulL48** [comment]
Sorry for the delay (Man's gotta eat), but no one touch this branch as I try to re-merge master into it before approving it.

**Comment by PaulL48** [comment]
Yo Marlin, thanks for getting on this quickly, it looks like Travis is still reporting an error in your test to do with the object type of a parameter. You should be able to run the tests locally from the command line via the `phpunit` command to see if they're passing

1) Tests\Unit\UserTest::testUserExist
TypeError: Argument 2 passed to Illuminate\Foundation\Testing\TestCase::assertDatabaseHas() must be of the type array, object given, called in /home/travis/build/PaulL48/SOEN341-SC4/tests/Unit/UserTest.php on line 19

**Comment by MarlinTheWiz** [comment]
@PaulL48 Sorry, dumb mistake. I forgot to turn the user variable into an array

**Comment by PaulL48** [comment]
Delete your branch at your leisure chief

**Pull request merged**
