### PR TITLE
Answer page styling

### PR DESCRIPTION
**Pull request by ratulkai93**
answers look more organized #70

### CODE REVIEW

**Comment by frodinm** [comment]
Nice updates!, I would recommend a different color for the question text. Also for the border, if the current index of the answer is not equal to 0, remove the top border in order to keep the consistency.

**Comment by frodinm** [comment]
Oh i noticed that "Question you have asked " is displayed even if the user that is signed in did not ask the question. Is that the intended behavior?

**Comment by GuiWukai** [comment]
nice I like the design

**Comment by PaulL48** [comment]
The branch being pulled here is out-of-sync with the master, being 23 commits behind and 13 commits ahead, so it's quite important that the pull is either resolved quickly, or is closed if the work has been moved to a different branch. @ratulkai93 @KhangZhengNg 

I would highly suggest that before this branch is merged (test_rz -> master), that you update it from the master branch and assure that it works (merge master -> test_rz). That way if there are any big problems that arise, they're isolated from master. This is done from the command line by entering 
```
git checkout test_rz
git merge master
```
Then, if everything works on the branch, I'll approve and merge asap

**Comment by ratulkai93** [comment]
I had issues with my test_rz file. So i made a different branch with mine and @KhangZhengNg s work more or less merged (test_rz2). can I commit that branch instead for the pull request#75?
or like create a new pull request and delete this one?

**Comment by PaulL48** [comment]
If I'm understanding correctly, you cannot switch the branch to be merged in a pull request. As per your suggestion of creating a new pull, that's probably the way to go, so here's what I suggest doing: Make a backup of any of your work that hasn't been moved to the other branch, close this pull request, delete the branch and submit a pull request on the other branch

**Pull request closed without merging**
