### PR TITLE
Perform setup for TravisCI databases and local Unit testing

### PR DESCRIPTION
**Pull request by PaulL48**
Important!
you can now run the php tests you've written locally via the "phpunit" command, which executes all the current tests. Try to assure that your tests are passing locally before committing.

As well, please include the line "use DatabaseMigrations;" in your unit test classes (in the actual class body) which will protect your databases from being affected when you run the tests locally by rolling back changes made after each test function.

### CODE REVIEW

**Comment by PaulL48** [comment]
This work is against issue #72 to add phpunit testing to the project

**Comment by PaulL48** [comment]
Oh, this also adds database seeding which Travis uses to populate the database with some test data before executing the tests. You can add some of your own if you need it for your tests under /database/seeds

**Comment by PaulL48** [comment]
Thanks for the speedy approval Philippe! Good luck with your studying

**Comment by frodinm** [comment]
Awesome job Paul!

**Pull request merged**
