### PR TITLE
Backend voting score

### PR DESCRIPTION
**Pull request by nirmal864**
added 
-votes table 
-votes controller
-votes model 
-routes created

### CODE REVIEW

**Comment by frodinm** [comment]
screen shot 2018-02-13 at 12 02 48 pm 
For front end we need something like this.

**Comment by nirmal864** [comment]
I made the changes on web.php just now.

**Comment by frodinm** [comment]
Shouldnt the api route take a specific id ?

**Comment by nirmal864** [comment]
needs some changes

**Pull request closed without merging**
