### PR TITLE
Tables Create

### PR DESCRIPTION
**Pull request by MarlinTheWiz**
Create Questions and Answers Table for SQL Database

### CODE REVIEW

**Comment by frodinm** [comment]
Please add the api routes for the front end as well. Do we need to run a php command to get it up and running on our local machine?

**Comment by PaulL48** [comment]
@MarlinTheWiz I would strongly recommend adding descriptions to all your pull requests and commits. This is one of the criteria on which we're being marked. On the command line, the -m parameter is broken into two parts: characters before the first newline are taken to be the title, characters after the newline are taken to be the description.

**Comment by PaulL48** [comment]
@frodinm Laravel's way of managing databases is as such. Templates for the databases are held in the repo by way of "Migration" classes. Any time changes are made to the migration classes (ex a new column is added) it's highly recommended to run "php artisan migrate:refresh" which will remake the whole database using any changes made in the migration files

**Comment by MarlinTheWiz** [comment]
@PaulL48 I implemented the requested changes, let me know if anything else should be changed

**Comment by PaulL48** [comment]
Class name was changed, so everything looks good.

**Comment by PaulL48** [comment]
This is a pull against #24 as the database infrastructure

**Pull request merged**
