### PR TITLE
Reactjs testing configuration

### LINKED ISSUE #18: Need to add test configurations for Reactjs

### PR DESCRIPTION
**Pull request by frodinm**
Added Reactjs testing configuration to resolve #18 . I also added eslint configs to decrease javascript errors.

### CODE REVIEW

**Comment by ACuriousSeaTurtle** [comment]
I've checked out your branch but I'm getting an error on the home page. I have run "composer update" just to be sure it wasn't dependency related. This could be due to not having a database currently in place on my laptop. Are there any steps that need to be performed before this works? ie. Installing something?

Could @philippelorange or @MarlinTheWiz check out this branch for review and approval?

**Comment by frodinm** [comment]
Ok I fixed all the issues related to the routing. 
@ACuriousSeaTurtle You might need to run npm run install to get everything working.

**Comment by frodinm** [comment]
oh, we need to make sure everyone is running the same laravel version, seems im running a slightly newer version

**Comment by ACuriousSeaTurtle** [comment]
This is an important pull request that has been pending for some time. I nominate that someone other than Philippe, Marlin or myself reviews and approves it. 

@KhangZhengNg @zhaoxing2788 @nirmal864 @ratulkai93 One of you should take the opportunity to thoroughly review and assure this pull request is in working order, then approve it. If you run into problems running the branch, ask the branch author (Fabrizio) here to clarify.

Also don't forget Meeting 5's decision. Once this pull request is closed, the 'Front-end' branch should be deleted.

**Comment by ACuriousSeaTurtle** [comment]
Regarding the laravel versioning, we need to be cautious of updating the project framework every time they release a new version. This is something that will be discussed in Meeting 6

**Pull request merged**
